---
driver:
  name: vagrant
  

provisioner:
  name: chef_zero
  data_path: test/integration

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec
#   format: doc

platforms:
  - name: centos-6.7
    driver:
      customize:
        memory: 256
     

suites:
  - name: default
    run_list:
      - recipe[tomcat::default]
    attributes: